import Vue from 'vue';
import App from './App.vue';

Vue.config.productionTip = false;

new Vue({
	render: h => h(App, {
		props: {
			choices: [
				/// Do
				['Start', 'Stop', 'Try more', 'Do less', 'Do more', 'Cut back on', 'Improve', 'Finish', 'Invent', 'Find', 'Solve', 'Investigate', 'Explore'],
				/// What
				[
					'Farting',
					'Running',
					'Playa hating',
					'Crushing it',
					'Eating',
					'Hugging',
					'Corduroy pants',
					'Murder',
					'Kickboxing',
					'Kickball',
					'Chillin',
					'Gambling',
					'Lying',
					'Stealing',
					'Identity theft',
					'Sneezing',
					'Vandalism',
					'High jinks',
					'Lollygagging',
					'Mischief',
					'Time travel',
					'Catfishing',
					'Screaming',
					'Recycling',
					'Brushing teeth',
					'Space travel',
					'Pulling yourself together',
					'Catching all the Pokemon',
					'Devil worshiping',
					'Paintball',
					'Mysticism',
					'Math',
					'Skateboarding',
					'Driving',
					'Cursing',
					'Seeing in color',
					'Making friends',
					'Sleeping',
					'Learning',
					'Speaking backwards',
					'Acrobatics',
					'Mind reading',
					'Reading',
					'Saving the planet',
					'Saving endangered species',
					'Day drinking',
					'Questioning',
					'Believing',
					'Loving',
					'Listening',
					'Dancing like everyone is watching',
					'Fast & Furious movies',
					'Voting',
					'Shopping',
					'Smoking',
					'Drinking',
					'Bathing',
					'Singing',
					'Magic tricks',
					'Making cookies',
					'Wetting pants',
					'Growing a mustache',
					'Getting taller',
					'Living',
					'Donating',
					'Helping',
					'Volunteering',
					'Shouting',
					'Hurting',
					'Writing',
					'Making money',
					'Banjo',
					'Caring',
					'Exercising',
					'Exercising demons',
					'Having emotions',
					'Meet dogs',
					'Eating meat',
					'Eating veggies',
					'Eating fruit',
					'Enjoying things',
					'World hunger',
					'Bad breath',
					'Superstitions',
					'Spooky things',
					'Fasting',
					'Cooking',
					'Traveling'
				],
				/// How/when/why/where
				[
					'on drugs',
					'before next week',
					'in January',
					'by February',
					'by March',
					'by April',
					'by June',
					'by July',
					'by August',
					'by September',
					'by October',
					'by November',
					'in December',
					'eventually',
					'maybe',
					'someday',
					'if you feel like it',
					'...or not. Who cares?',
					'in space',
					'for science',
					'for Christ',
					'immediately',
					'right now',
					'next Tuesday',
					'carefully',
					'quickly',
					'Seriously.',
					'everyday',
					'most days',
					'once a month',
					'once a week',
					'twice daily',
					'in the potty',
					'with friends',
					'with family',
					'with neighbors',
					'with animals',
					'for animals',
					'for kids',
					'outside',
					'never',
					'on Netflix',
					'on Amazon',
					'with ghosts',
					'in Europe',
					'in pants',
					'eleven times',
					'fifty times',
					'one hundred times',
					'sixty times',
					'ten times',
					'twice',
					'thrice',
					'a few times',
					'at least once',
					'on airplanes',
					'indoors',
					'every night',
					'with parents',
					'just for fun',
					'and write about it',
					'for myself',
					'around others',
					'around children',
					'around schools',
					'on the streets',
					'around the house',
					'downstairs',
					'by the shed',
					'by moonlight',
					'on the sea',
					'under the sea',
					'upstream',
					'online',
					'in bed',
					'forever',
					'until Friday',
					'until summer',
					'until fall',
					'until winter'
				]
			]
		}
	}),
}).$mount('#app');
