import 'normalize.css';
import 'typebase.css';
import Vue from 'vue';
import App from './App.vue';

Vue.config.productionTip = false;

new Vue({
	render: h =>
		h(App, {
			props: {
				choices: [
					/// Do
					[
						'Start',
						'Stop',
						'Try more',
						'Do less',
						'Do more',
						'Cut back on',
						'Improve',
						'Finish',
						'Invent',
						'Find',
						'Solve',
						'Investigate',
						'Explore',
						'Attempt',
						'Quit',
						'Avoid',
						'Get better at',
						'Learn',
						'See',
						'Consider',
						'Retry'
					],
					/// What
					[
						'farting',
						'running',
						'playa\' hating',
						'crushing it',
						'eating',
						'hugging',
						'corduroy pants',
						'murder',
						'kickboxing',
						'cartoon reruns',
						'ancient wisdom',
						'kickball practice',
						'chillin',
						'gambling',
						'lying',
						'stealing',
						'identity theft',
						'sneezing',
						'vandalism',
						'high jinks',
						'lollygagging',
						'mischief',
						'time travel',
						'catfishing',
						'screaming',
						'recycling',
						'brushing teeth',
						'space travel',
						'pulling yourself together',
						'devil worshiping',
						'face tattoos',
						'paintball',
						'mysticism',
						'math',
						'skateboarding',
						'driving',
						'cursing',
						'seeing in color',
						'making friends',
						'sleeping',
						'learning',
						'speaking backwards',
						'acrobatics',
						'mind reading',
						'reading',
						'saving the planet',
						'saving endangered species',
						'day drinking',
						'questioning',
						'believing',
						'loving',
						'listening',
						'dancing like everyone is watching',
						'Fast & Furious movies',
						'voting',
						'shopping',
						'smoking',
						'drinking',
						'bathing',
						'singing',
						'magic tricks',
						'making cookies',
						'wetting pants',
						'growing a mustache',
						'getting taller',
						'shrinking',
						'avoiding direct sunlight',
						'keeping eye contact',
						'living',
						'donating',
						'helping',
						'volunteering',
						'shouting',
						'hurting',
						'writing',
						'making money',
						'banjo',
						'caring',
						'exercising',
						'exercising demons',
						'having emotions',
						'meet dogs',
						'eating meat',
						'eating veggies',
						'eating fruit',
						'enjoying things',
						'world hunger',
						'bad breath',
						'superstitions',
						'spooky things',
						'fasting',
						'cooking',
						'traveling',
						'tickling',
						'gaining weight',
						'deadly, exotic foods',
						'erotic fiction',
						'not dying',
						'learning a new language',
						'reviving Latin',
						'poisoning rivals',
						'telling secrets',
						'juicing',
						'new pastas',
						'listening to Trump',
						'cuts & bruises',
						'giving bad advice',
						'forming K-Pop bands',
						'painting self-portraits',
						'volunteering',
						'using vowels',
						'adoring baby animals',
						'being shy',
						'having nightmares',
						'ruining Christmas',
						'falconry',
						'cleaning up',
						'being passive aggressive',
						'grow reptilian features',
						'leading the revolt'
					],
					/// How/when/why/where
					[
						'on drugs',
						'before next week',
						'in January',
						'by February',
						'by March',
						'by April',
						'by June',
						'by July',
						'by August',
						'by September',
						'by October',
						'by November',
						'in December',
						'eventually',
						'maybe',
						'someday',
						'if you feel like it',
						'...or not. Who cares?',
						'in space',
						'for science',
						'for Christ',
						'immediately',
						'right now',
						'next Tuesday',
						'carefully',
						'quickly',
						'– seriously.',
						'everyday',
						'most days',
						'once a month',
						'once a week',
						'twice daily',
						'in the potty',
						'with friends',
						'with family',
						'with neighbors',
						'with animals',
						'for animals',
						'for kids',
						'outside',
						'never',
						'on Netflix',
						'on Amazon',
						'on Twitter',
						'with Google',
						'on open mic night',
						'in private',
						'in secret',
						'with ghosts',
						'in Europe',
						'in pants',
						'eleven times',
						'fifty times',
						'one hundred times',
						'sixty times',
						'ten times',
						'twice',
						'a few times',
						'at least once',
						'on airplanes',
						'indoors',
						'every night',
						'with parents',
						'just for fun',
						'and write about it',
						'in a novel',
						'as a screenplay',
						'in a dream',
						'on a dare',
						'for myself',
						'around others',
						'around children',
						'around schools',
						'on the streets',
						'around the house',
						'downstairs',
						'by the shed',
						'by moonlight',
						'on the sea',
						'under the sea',
						'upstream',
						'online',
						'in bed',
						'forever',
						'until Friday',
						'until summer',
						'until fall',
						'until winter',
						'to music',
						'in the dark',
						'before my birthday',
						'at an amusement park',
						'cold turkey',
						'to get rich',
						'but say I didn\'t',
						'for your country',
						'for ten dollars',
						'or else',
						'or bust',
						'or die',
						'– unless it\'s too hard',
						'backwards',
						'with my eyes closed',
						'wearing a turtleneck',
						'with one hand behind my back',
						'with enemies',
						'post-haste',
						'at last',
						'once and for all',
						'after meals',
						'on a date',
						'at sea',
						'through interpretive dance'
					]
				]
			}
		})
}).$mount('#app');
